DROP DATABASE IF EXISTS employees_db;
CREATE DATABASE employees_db;

use employees_db;

CREATE TABLE DEPARTMENTS (
   id INT NOT NULL AUTO_INCREMENT,
   title VARCHAR(30) NOT NULL,
   PRIMARY KEY (id)
);

CREATE TABLE ROLES (
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(30) NOT NULL,
    department_id INT NOT NULL,
    salary INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (department_id) REFERENCES DEPARTMENTS(id) ON DELETE CASCADE
);

CREATE TABLE EMPLOYEES(
    id INT NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULl,
    role_id INT NOT NULL,
    manager_id INT REFERENCES EMPLOYEES(id), 
    PRIMARY KEY (id),
    FOREIGN KEY (role_id) REFERENCES ROLES(id)
);
